name: tf114
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.10
    - tensorflow-gpu=1.14.0
    - scipy=1.6.2
    - pydoe=0.3.8
    - ipykernel=5.3.4
    - matplotlib=3.4.2
    - seaborn=0.9.0
    - jupyter=1.0.0