name: tf24
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8.10
    - cudatoolkit=11
    - cudnn=8
    - defaults::scipy=1.6.2
    - defaults::ipykernel=5.3.4
    - defaults::matplotlib=3.4.2
    - tensorflow-probability=0.12.2
    - pydoe=0.3.8
    - jupyter=1.0.0
    - pytest=6.2.4
    - pip
    - pip:
        - tensorflow-gpu==2.4.1